CREATE DATABASE IF NOT EXISTS soccer CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'soccer'@'%' IDENTIFIED BY 'soccer-local-password';
GRANT ALL PRIVILEGES ON soccer.* TO 'soccer'@'%';
FLUSH PRIVILEGES;
